config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :search, only: [:index]

  authenticate :user, lambda { |u| u.admin? } do 
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'perfect'
      post 'bullshit'
      post 'cancel'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :subscriptions, only: :index
  resources :searches, only: :index

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions
    resources :answers, concerns: [:votable, :commentable] do
      post 'best', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  resources :attaches, only: [:destroy]

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Attachable
  include Commentable
  include Reputationable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user

  scope :lastday, -> { where(updated_at: Time.now - 1) }

  after_create :create_subscribe_for_author
  after_create :notify_the_subscriber
  after_create :update_reputation
  #after_create :calculate_reputation

  validates :title,   presence: true, length: { minimum: 5, maximum: 140 }
  validates :body,    presence: true, length: { minimum: 5, maximum: 1000 }
  validates :user_id, presence: true

  private

  def notify_the_subscriber
    AnswerNoticeJob.perform_later(self)
  end

  def create_subscribe_for_author
    Subscription.create(user: self.user, question: self)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController

  authorize_resource

  # Method: GET
  # URL: http://localhost:3000/oauth/token
  # RequestHeader: Content-Type
  #         Value: application/x-www-form-urlencoded
  # client_id= 'Application Id' &
  # client_secret= 'Secret' &
  # code= 'Authorization code' &
  # grant_type=authorization_code&
  # redirect_uri=urn:ietf:wg:oauth:2.0:oob

  def index # http://localhost:3000/api/v1/questions.json?access_token=
    @questions = Question.all
    #respond_with @question.to_json(include: :answers)
    respond_with @questions, each_serializer: QuestionSerializer
  end

  def show
    @question = Question.find(params[:id])
    respond_with @question, serializer: QuestionSerializer
  end

  def create
    #respond_with(@question = current_user.questions.create(question_params))
    @question = Question.create(question_params.merge(user: current_resource_owner))
    respond_with @question

    #respond_with current_resource_owner.questions.create(question_params)
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, attaches_attributes: [:id, :file, :_destroy])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy, :perfect, :bullshit, :cancel]
  before_action :build_answer, only: [:show]

  respond_to :json

  authorize_resource

  def index
    respond_with(@questions = Question.all)
  end

  def show
    respond_with @question
  end

  def new
    respond_with (@question = Question.new)
  end

  def edit
  end

  def create
    respond_with (@question = current_user.questions.create(question_params))
    PrivatePub.publish_to '/questions/new', question: @question.to_json if @question.save
  end

  def update
    @question.update(question_params)
    respond_with @question
  end

  def destroy
    respond_with (@question.destroy)
  end

  private

  def build_answer
    @answer = @question.answers.build
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, attaches_attributes: [:id, :file, :_destroy])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_attach_fields.html.slim
.fields
  = f.label :file
  = f.file_field :file
= link_to_remove_association 'delete file? ', f

app/views/questions/_form.html.slim
= form_for @question do |f|
  .field
    = f.label :title
    = f.text_field :title, size: 61
    = f.label :body
    = f.text_area :body, rows: 5, cols: 60
  .attaches_form
    -if @question.new_record?
      = f.fields_for :attaches, @question.attaches.build do |a|
        = render 'attach_fields', f: a
      .links
        p= link_to_add_association 'add file', f, :attaches
    -else
      .attaches_form
        = link_to_add_association 'add file', f, :attaches
    = f.submit "Подать вопрос", class: 'btn btn-success btn-sm'

app/views/questions/_questions_list.html.slim
td = question.user_id
td = link_to question.title, question_path(question)
td = question.answers.count
td = question.created_at.strftime("%d.%m.%Y")
td = question.updated_at.strftime("%d.%m.%Y") if question.created_at != question.updated_at
td
  div class="votes_count"
    = "#{question.votes.sum("score")} / #{question.votes_count}"
td
  - if can?(:cancel, question)
    = link_to("Cancel vote", cancel_question_path(question), method: :post, remote: true, class: 'btn btn-danger btn-xs best-answer-link')
  - if can?(:perfect, question) && can?(:bullshit, question)
    = link_to("Perfect", perfect_question_path(question), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
    i &nbsp;or&nbsp;
    = link_to("Bullshit", bullshit_question_path(question), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
  - if can?(:edit, question)
    i= link_to " Edit? ", edit_question_path(question)
  - if can?(:destroy, question)
    i= link_to " Del? ", question, method: :delete, data: {confirm: "Подтверждение удаления"}

app/views/questions/bullshit.js.erb
$(".question_<%= @question.id %>").replaceWith("<tr class='question_<%= @question.id %>'>" + '<%= j render 'questions/questions_list', question: @question %>' + "</tr>");

app/views/questions/cancel.js.erb
$(".question_<%= @question.id %>").replaceWith("<tr class='question_<%= @question.id %>'>" + '<%= j render 'questions/questions_list', question: @question %>' + "</tr>");

app/views/questions/edit.html.slim
h1 Редактирование вопроса
= render partial: "form"

app/views/questions/index.html.slim
- unless @questions.empty?
  div class="panel panel-default"
    div class="panel-heading" Список вопросов:
    table class="table" id="questions"
      thead
        tr
          th User:
          th Title:
          th Ответов:
          th Создан:
          th Изменен:
          th Голосов:
          th Действие:
      tbody
        - cache collection_cache_key_for :question do
          - @questions.each do |question|
            tr class="question_#{question.id}"
              = render 'questions_list', question: question
- else
  h4 Еще нет вопросов
= subscribe_to "/questions/new"

app/views/questions/new.html.slim
h1 Задайте вопрос:
= render partial: "form"

app/views/questions/perfect.js.erb
$(".question_<%= @question.id %>").replaceWith("<tr class='question_<%= @question.id %>'>" + '<%= j render 'questions/questions_list', question: @question %>' + "</tr>");

app/views/questions/show.html.slim
- cache @question do
  .question data={question_id: "#{@question.id}"}
    font color="green" Количество ответов: &nbsp
    = @question.answers.count
    br
    font color="green" ID пользователя создавшего вопрос: &nbsp
    = @question.user_id
    br
    font color="green" Создан/изменен: &nbsp
    = @question.created_at.strftime("%d-%m-%y") + " / " + @question.updated_at.strftime("%d-%m-%y")
    br
    font color="blue" Вопрос №
    = @question.id
    |&nbsp;
    font color="blue" Заголовок: &nbsp
    = @question.title
    |&nbsp;
    = render 'subscriptions/button'
    div class='votes_count'
      font color="blue" Голосов:&nbsp
      ="#{@question.votes.sum("score")} / #{@question.votes_count} "
      - if can?( :cancel, @question )
        = link_to("Cancel vote", cancel_question_path(@question), method: :post, remote: true, class: 'btn btn-danger btn-xs best-answer-link')
      - if can?(:perfect, @question )
        = link_to("Perfect", perfect_question_path(@question), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
        i &nbsp;or&nbsp;
      - if can?(:bullshit, @question )
        = link_to("Bullshit", bullshit_question_path(@question), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
    p
      font color="blue" Содержание: &nbsp
      = @question.body
    - if can?(:edit, @question)
      = link_to "Редактировать вопрос?", edit_question_path, class: 'btn btn-default btn-xs edit-question-link'
      |&nbsp;
    - if can?(:destroy, @question)
      = link_to "Del?", @question, method: :delete, data: {confirm: "Подтверждение удаления"}, class: 'btn btn-danger btn-xs'
    p
    font color="blue" Attachments: &nbsp
    - @question.attaches.each do |a|
      i id="attach_#{a.id}"
        = link_to a.file.identifier, a.file.url
        - if can?(:destroy, a)
          = link_to "Удалить #{a.file.identifier}?", attach_path(a), method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: "Подтверждение удаления"}, remote: true
    p Комментарии:
    .comments
      = render 'comments/list', parent: @question

  .answers
    = render @question.answers.firstbest

  = form_for [@question, @answer], remote: true do |f| #, data: {type: :json} do |f|
    .answer_text_body
      = f.label :body, 'Your answer'
      = f.text_area :body, size: "40"
    .answer_attach
      = f.fields_for :attaches, @answer.attaches.build do |a|
        = render 'attach_fields', f: a
        = link_to_add_association 'add file', f, :attaches
    .answer_text_body
      = f.submit 'Ответить'
.answer-errors
.comments-errors

= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"