config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :search, only: [:index]

  authenticate :user, lambda { |u| u.admin? } do 
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'perfect'
      post 'bullshit'
      post 'cancel'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :subscriptions, only: :index
  resources :searches, only: :index

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions
    resources :answers, concerns: [:votable, :commentable] do
      post 'best', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  resources :attaches, only: [:destroy]

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Attachable
  include Commentable
  include Reputationable

  belongs_to :question, touch: true
  belongs_to :user

  validates :body,        presence: true, length: { minimum: 2, maximum: 1000 }
  validates :question_id, presence: true
  validates :user_id,     presence: true

  scope :firstbest, -> { order('best DESC, created_at') }

  after_create { update_reputation }
  after_create { AnswerNoticeJob.perform_later(self) }
  after_create { Subscription.find_or_initialize_by(user: self.user, question: self.question).save! }
  #after_create :update_reputation, :notice_subscribers
  #after_create :calculate_reputation

  def best_answer
    oldbest = question.answers.find_by(best: true)
    oldbest.update_attributes(best: false) if oldbest
    update_attributes(best: true)
  end

#  private
#
#  def notice_subscribers
#    AnswerNoticeJob.perform_later(self)
#  end
#
#  def create_subscribe_for_author_of_answer
#    Subscription.find_or_initialize_by(user: self.user, question: self.question).save!
#  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :load_answer, only: [:destroy, :update, :best, :perfect, :bullshit, :cancel]
  before_action :load_question_answer, only: [:best, :perfect, :bullshit, :cancel]
  after_action :publish_answer, only: [:create]

  respond_to :js
  respond_to :json, only: :create

  authorize_resource

  def update
    @answer.update(answer_params)
    respond_with @answer
  end

  def create
    @question = Question.find(params[:question_id])
    respond_with(@answer = @question.answers.create(answer_params))
  end

  def destroy
    @answer.destroy
  end

  def best
    @answer.best_answer
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
    @question = @answer.question
  end

  def answer_params
    params.require(:answer).permit(:body, attaches_attributes: [:id, :file, :_destroy]).merge(user_id: current_user.id)
  end

  def publish_answer
    PrivatePub.publish_to("/questions/#{@question.id}/answers", answer: @answer.to_json) if @answer.valid?
  end

  def load_question_answer
    @question = @answer.question
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController

  authorize_resource

  # Method: GET
  # URL: http://localhost:3000/oauth/token
  # RequestHeader: Content-Type
  #         Value: application/x-www-form-urlencoded
  # client_id= 'Application Id' &
  # client_secret= 'Secret' &
  # code= 'Authorization code' &
  # grant_type=authorization_code&
  # redirect_uri=urn:ietf:wg:oauth:2.0:oob

  def index # http://localhost:3000/api/v1/answers.json?access_token=
    respond_with(@answers = Answer.all)
  end

  def show
    @answer = Answer.find(params[:id])
    respond_with @answer, serializer: AnswerSerializer
  end

  def create
    @question = Question.find(params[:question_id])
    #respond_with(@answer = @question.answers.create(answer_params))
    respond_with(@answer = @question.answers.create(answer_params.merge(user: current_resource_owner)))
    #respond_with(@answer = @question.answers.create(answer_params.merge({user_id: current_resource_owner.id})))
  end

  private

  def answer_params
    #params.require(:answer).permit(:body, attaches_attributes: [:id, :file, :_destroy]).merge(user_id: current_user.id)
    params.require(:answer).permit(:body)
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  - cache answer do
    = div_for answer, data: {answer_id: "#{answer.id}"} do
      font color="#CC0000"
        b = answer.user_id
      = answer.body
      - answer.attaches.each do |a|
        b id="attach_#{a.id}"
          = link_to a.file.identifier, a.file.url
          - if can?(:destroy, a)
            = link_to "Удалить #{a.file.identifier}?", attach_path(a), method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: "Подтверждение удаления"}, remote: true
      b class="votes_count"
        =" #{answer.votes.sum("score")} / #{answer.votes_count} "
      - if can?( :cancel, answer )
        = link_to("Cancel vote", cancel_answer_path(answer), method: :post, remote: true, class: 'btn btn-danger btn-xs best-answer-link')
      - if can?( :perfect, answer )
        = link_to("Perfect", perfect_answer_path(answer), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
        i &nbsp;or&nbsp;
      - if can?( :bullshit, answer )
        = link_to("Bullshit", bullshit_answer_path(answer), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
      - if can?(:best, answer)
        - if answer.best
          b 'best answer'
        - else
          = link_to('Best', best_answer_path(answer), method: :post, remote: true, class: 'btn btn-primary btn-xs best-answer-link')
      - if can?(:edit, answer)
        = link_to 'Редактировать ответ?', '', class: 'btn btn-default btn-xs edit-answer-link', data: { answer_id: answer.id }, remote: true
      - if can?(:destroy, answer)
        = link_to 'Del answer?', answer, method: :delete, class: 'btn btn-danger btn-xs', data: {confirm: "Подтверждение удаления"}, remote: true
        = form_for answer, method: "patch", remote: true, html: { id: "edit-answer-#{answer.id}" } do |f|
          .answer_text_body
            = f.label :body, 'Текст ответа:'
            = f.text_area :body
          .answer_attach
            = f.fields_for :attaches do |a|
              = render 'questions/attach_fields', f: a
              .links
                p= link_to_add_association 'add file', f, :attaches
          .answer_text_body
            = f.submit 'Сохранить'
      .comments id="#{answer.id}"
        = render 'comments/list', parent: answer
        = subscribe_to "/answers/#{answer.id}/comments"

app/views/answers/_attach_fields.html.slim
.fields
  = f.label :file
  = f.file_field :file
= link_to_remove_association 'delete file? ', f

app/views/answers/best.js.erb
$('.answers').html('<%= j render @question.answers.firstbest %>');

app/views/answers/bullshit.js.erb
$('.answers').html('<%= j render @question.answers.firstbest %>');

app/views/answers/cancel.js.erb
$('.answers').html('<%= j render @question.answers.firstbest %>');

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% end %>

app/views/answers/destroy.js.erb
$(".answers #answer_<%= @answer.id %>").remove();

app/views/answers/perfect.js.erb
$('.answers').html('<%= j render @question.answers.firstbest %>');

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
    <% @answer.errors.full_messages.each do |message| %>
        $('.answer-errors').html('<%= j message %>');
    <% end %>
<% else %>
    $('#answer_<%= @answer.id %>').replaceWith('<%= j render @answer %>');
    $('.edit-answer-link').click(function(e) {
        e.preventDefault();
        $(this).hide();
        answer_id = $(this).data('answerId');
        $('form#edit-answer-' + answer_id).show();
    });
<% end %>