config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :search, only: [:index]

  authenticate :user, lambda { |u| u.admin? } do 
    mount Sidekiq::Web => '/sidekiq'
  end
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'questions#index'

  concern :votable do
    member do
      post 'perfect'
      post 'bullshit'
      post 'cancel'
    end
  end

  concern :commentable do
    resources :comments
  end

  resources :subscriptions, only: :index
  resources :searches, only: :index

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions
    resources :answers, concerns: [:votable, :commentable] do
      post 'best', on: :member
    end
  end

  namespace :api do
    namespace :v1 do
      resource :profiles do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions do
        resources :answers
      end
    end
  end

  resources :attaches, only: [:destroy]

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :user
  belongs_to :question
  validates :user_id, presence: true
  validates :question_id, presence: true
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_subscription, only: :destroy
  respond_to :js
  authorize_resource

  def index
    @subscriptions = Subscription.all
  end

  def create
    @question = Question.find(params[:question_id])
    #respond_with(@subscription = Subscription.create(question: @question, user: current_user))
    respond_with(@subscription = current_user.subscriptions.create(question: @question))
  end

  def destroy
    #@subscription = Subscription.where(user: current_user, question: @question).first
    respond_with (@subscription.destroy)
    #respond_with(@subscription = current_user.subscriptions.destroy(question: @question))
  end

  private

  def load_subscription
    @subscription = Subscription.find(params[:id])
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_button.html.slim
.subscribe
  - if can?(:create, Subscription.new(question: @question, user: current_user))
    - unless Subscription.exists?(user: current_user, question: @question)
      = link_to("Subscribe", question_subscriptions_path(@question), method: :post, remote: true, class: 'btn btn-primary btn-xs')
    - else
      = link_to("Unsubscribe", subscription_path(@question), method: :delete, remote: true, class: 'btn btn-danger btn-xs')

app/views/subscriptions/create.js.erb
$('.subscribe').replaceWith('<%= j render 'subscriptions/button' %> ');

app/views/subscriptions/destroy.js.erb
$('.subscribe').replaceWith('<%= j render 'subscriptions/button' %> ');

app/views/subscriptions/index.html.slim
- unless @subscriptions.empty?
  table class="table" id="subscriptions"
    thead
      tr
        th subscription.id
        th user.email
        th question.id
    tbody
      - @subscriptions.each do |subs|
        tr
          td= subs.id
          td= subs.user.email
          td= subs.question.id